name       : libspeex
version    : 1.2.0
release    : 5
source     :
    - https://github.com/xiph/speex/archive/Speex-1.2.0.tar.gz : 4781a30d3a501abc59a4266f9bbf8b1da66fd509bef014697dc3f61e406b990c
    - https://github.com/xiph/speexdsp/archive/SpeexDSP-1.2.0.tar.gz : d7032f607e8913c019b190c2bccc36ea73fc36718ee38b5cdfc4e4c0a04ce9a4
homepage   : https://www.speex.org/
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : Audio compression format designed for speech and its converter application
description: |
    Speex is an Open Source/Free Software patent-free audio compression format designed for speech. The Speex Project aims to lower the barrier of entry for voice applications by providing a free alternative to expensive proprietary speech codecs. The package also contains a command-line tool to convert to/from Speex codec.
    This package also contains SpeexDSP, a patent-free, Open Source/Free Software DSP library.
emul32     : yes
builddeps  :
    - pkgconfig32(ogg)
environment: |
    export SPEEXDSP_CFLAGS="-I$installdir/usr/include"
    export SPEEXDSP_LIBS="-L$installdir%libdir% -lspeexdsp"
setup      : |
    tar xf $sources/SpeexDSP-*.tar.gz
    pushd speexdsp-*
        %reconfigure --disable-static
        %make
        %make_install
    popd

    %autogen --disable-static --enable-binaries
build      : |
    %make
install    : |
    %make_install
