name        : libspeex
version     : 1.2.1
release     : 3
source      :
    - http://downloads.xiph.org/releases/speex/speex-1.2rc1.tar.gz : 342f30dc57bd4a6dad41398365baaa690429660b10d866b7d508e8f1179cb7a6
homepage    : http://www.speex.org/
license     :
    - BSD-2-Clause
summary     : Audio compression format designed for speech and its converter application
builddeps   :
    - pkgconfig(ogg)
    - pkgconfig32(ogg)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description : |
    speex is an Open Source/Free Software patent-free audio compression format designed for speech. The Speex Project aims to lower the barrier of entry for voice applications by providing a free alternative to expensive proprietary speech codecs. The package also contains a command-line tool to convert to/from Speex codec
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
